# **`IMPORTAMOS LIBRERIAS`**

In [ ]:
import pandas as pd
import numpy as np
import random
from datetime import datetime, timedelta

# **GENERACIÓN DIMENSION FECHA**

In [ ]:
start_date = datetime(2022,1,1)
end_date = datetime(2024,12,31)

dates = pd.date_range(start_date, end_date)

dim_date = pd.DataFrame({
    "full_date": dates
})

dim_date["date_id"] = dim_date["full_date"].dt.strftime("%Y%m%d").astype(int)
dim_date["day"] = dim_date["full_date"].dt.day
dim_date["month"] = dim_date["full_date"].dt.month
dim_date["month_name"] = dim_date["full_date"].dt.strftime("%B")
dim_date["quarter"] = dim_date["full_date"].dt.quarter
dim_date["year"] = dim_date["full_date"].dt.year
dim_date["week_day"] = dim_date["full_date"].dt.strftime("%A")

dim_date = dim_date[[
    "date_id",
    "full_date",
    "day",
    "month",
    "month_name",
    "quarter",
    "year",
    "week_day"
]]

dim_date.head()

    date_id  full_date  day  month month_name  quarter  year   week_day
0  20220101 2022-01-01    1      1    January        1  2022   Saturday
1  20220102 2022-01-02    2      1    January        1  2022     Sunday
2  20220103 2022-01-03    3      1    January        1  2022     Monday
3  20220104 2022-01-04    4      1    January        1  2022    Tuesday
4  20220105 2022-01-05    5      1    January        1  2022  Wednesday

# **GENERACIÓN DIMENSIÓN CLIENTES**

In [ ]:
#Creamos las listas

first_names_male = ["Juan","Carlos","Luis","Pedro","Andrés",
                    "Miguel","Jorge","David","Daniel","Fernando"]
first_names_female = ["María","Ana","Laura","Sofía","Paula","Camila",
                      "Valentina","Andrea","Carolina","Diana"]

last_names = ["Gómez","Rodríguez","Martínez","López","Hernández",
              "García","Pérez","Sánchez","Ramírez","Torres"]

cities = [
    "Bogotá",
    "Medellín",
    "Cali",
    "Barranquilla",
    "Cartagena",
    "Bucaramanga",
    "Pereira",
    "Manizales",
    "Santa Marta",
    "Ibagué"
]

segments = ["Regular","Premium","VIP"]

In [ ]:
#Generamos los clientes

num_customers = 1500

customers = []

start_date = datetime(2020,1,1)
end_date = datetime(2024,12,31)

for i in range(num_customers):

    gender = random.choice(["Male","Female"])

    if gender == "Male":
        name = random.choice(first_names_male)
    else:
        name = random.choice(first_names_female)

    last = random.choice(last_names)

    full_name = name + " " + last

    age = random.randint(18,65)

    city = random.choice(cities)

    registration_date = start_date + timedelta(
        days=random.randint(0,(end_date-start_date).days)
    )

    segment = random.choices(
        segments,
        weights=[0.7,0.2,0.1]
    )[0]

    customers.append([
        full_name,
        gender,
        age,
        city,
        registration_date,
        segment
    ])

In [ ]:
#Creamos el DataFrame

dim_customers = pd.DataFrame(customers, columns=[
    "full_name",
    "gender",
    "age",
    "city",
    "registration_date",
    "customer_segment"
])

dim_customers.head()

,full_name,gender,age,city,registration_date,customer_segment
0,Luis Gómez,Male,58,Bogotá,2020-01-14,Regular
1,Carlos Martínez,Male,31,Ibagué,2022-07-18,Regular
2,Carolina Torres,Female,22,Bogotá,2024-03-20,Regular
3,Jorge Torres,Male,62,Bucaramanga,2022-02-01,Premium
4,Miguel Sánchez,Male,50,Bucaramanga,2020-08-23,Regular

# **GENERACIÓN DIMENSIÓN CATEGORIAS**

In [ ]:
categories = [
    [1, "Electronics"],
    [2, "Furniture"],
    [3, "Clothing"],
    [4, "Sports"],
    [5, "Food"]
]

In [ ]:
#Creamos el DataFrame
dim_category = pd.DataFrame(categories, columns=[
    "category_id",
    "category_name"
])

dim_category

   category_id category_name
0            1   Electronics
1            2     Furniture
2            3      Clothing
3            4        Sports
4            5          Food

# **GENERACIÓN DE DIMENSIÓN PRODUCTOS**

In [ ]:
products = [
    ("Laptop",1),
    ("Mouse",1),
    ("Keyboard",1),
    ("Monitor",1),
    ("Tablet",1),
    ("Headphones",1),

    ("Office Chair",2),
    ("Desk",2),
    ("Bookshelf",2),
    ("Lamp",2),
    ("Drawer Cabinet",2),

    ("T-Shirt",3),
    ("Jeans",3),
    ("Jacket",3),
    ("Sneakers",3),
    ("Hat",3),

    ("Basketball",4),
    ("Football",4),
    ("Tennis Racket",4),
    ("Yoga Mat",4),
    ("Dumbbells",4),

    ("Protein Bar",5),
    ("Energy Drink",5),
    ("Coffee",5),
    ("Chocolate",5),
    ("Granola",5)
]

In [ ]:
#Generamos los productos
data = []

for i, (product, category) in enumerate(products, start=1):

    data.append({
        "product_id": i,
        "product_name": product,
        "category_id": category
    })

In [ ]:
#Creamos el DataFrame
df_products = pd.DataFrame(data)

df_products.head()

   product_id product_name  category_id
0           1       Laptop            1
1           2        Mouse            1
2           3     Keyboard            1
3           4      Monitor            1
4           5       Tablet            1

# **GENERACIÓN DE REGIÓN**

In [ ]:
regions = [
    "North America",
    "South America",
    "Europe",
    "Asia",
    "Africa"
]

In [ ]:
#Creamos el DateFrame
dim_region = pd.DataFrame({
    "region_name": regions
})

dim_region.head()

     region_name
0  North America
1  South America
2         Europe
3           Asia
4         Africa

# **GENERACIÓN DE CHANNEL**

In [ ]:
channels = [
    "Online Store",
    "Marketplace",
    "Physical Store",
    "Mobile App",
    "Call Center"
]

In [ ]:
#Creamos el DataFrame
dim_channel = pd.DataFrame({
    "channel_name": channels
})

dim_channel.head()

     channel_name
0    Online Store
1     Marketplace
2  Physical Store
3      Mobile App
4     Call Center

# **GENERAMOS FACT_SALES**

In [ ]:
# Cargar los date_id reales
dates = pd.read_csv("dim_date_ids.csv")
date_ids = dates["DATE_ID"].tolist()

products = pd.read_csv("dim_products.csv")

product_ids = products.index + 1
product_ids = product_ids.tolist()

fact_sales = []

num_sales = 50000

for i in range(num_sales):

    date_id = random.choice(date_ids)

    customer_id = random.randint(1,1500)

    product_id = random.choice(product_ids)

    quantity = random.randint(1,5)

    unit_price = round(random.uniform(20,2000),2)

    total_amount = round(quantity * unit_price,2)

    fact_sales.append([
        date_id,
        customer_id,
        product_id,
        quantity,
        unit_price,
        total_amount
    ])

In [ ]:
#Creamos el DataFrame
fact_sales = pd.DataFrame(fact_sales, columns=[
    "date_id",
    "customer_id",
    "product_id",
    "quantity",
    "unit_price",
    "total_amount"
])
print(fact_sales)

        date_id  customer_id  product_id  quantity  unit_price  total_amount
0      20230920         1373          13         2      544.81       1089.62
1      20230824          927          25         5     1751.11       8755.55
2      20230101          610          15         3     1696.71       5090.13
3      20241102           64          13         4      482.83       1931.32
4      20220726          764          20         2      906.94       1813.88
...         ...          ...         ...       ...         ...           ...
49995  20230731          464          19         3      275.86        827.58
49996  20240501          377          12         5     1907.44       9537.20
49997  20230729          676          22         2     1212.06       2424.12
49998  20241218          366          21         3      886.63       2659.89
49999  20240510          352          11         2       33.36         66.72

[50000 rows x 6 columns]

# **EXPORTACIÓN DE ARCHIVOS**

In [ ]:
#CSV DIM_DATA
dim_date.to_csv("dim_date.csv", index=False)

In [ ]:
#CSV DIM_CUSTOMERS
dim_customers.to_csv("dim_customers.csv", index=False)

In [ ]:
#CSV DIM_CATEGORY
dim_category.to_csv("dim_category.csv", index=False)

In [ ]:
#CSV DIM_PRODUCTS
df_products.to_csv("dim_products.csv", index=False)

In [ ]:
#CSV DIM_REGION
dim_region.to_csv("dim_region.csv", index=False)

In [ ]:
#CSV DIM_CHANNEL
dim_channel.to_csv("dim_channel.csv", index=False)

In [ ]:
#CSV FACT_SALES
fact_sales.to_csv("fact_sales.csv", index=False)